### ISSUE TITLE
can't step through environment because of _last_action initialization

### ISSUE THREAD

**Issue by limbryan** [sotetsuk/pgx-minatar#3]
Hi,

I have some issues running the minatar environments. They seem to be throwing an error on this line:  https://github.com/sotetsuk/pgx-minatar/blob/049944db584c82962348aec02be46b8f2b2bf1e6/pgx_minatar/seaquest.py#L154 

This is because _last action is initialised as a single integer and action is a 6-dimensional array. Is this normal behaviour? Thanks!

**Comment by limbryan** [comment]
Hi, thanks for the prompt reply. Here is the block of code I used which is meant to be just the example code essentially. I am using a fixed action just to test.

```
import jax
import jax.numpy as jnp
import pgx
from pgx.experimental import auto_reset

env = pgx.make("minatar-seaquest")
init = jax.jit(jax.vmap(env.init))
step = jax.jit(jax.vmap(env.step))
step = jax.vmap(auto_reset(env.step, env.init))

batch_size = 1024

random_key = jax.random.PRNGKey(42)
random_key, init_state_key = jax.random.split(random_key)
keys = jax.random.split(init_state_key, batch_size)
state = init(keys)  # vectorized states

while not (state.terminated | state.truncated).all():
    random_key, action_key = jax.random.split(random_key)
    action = jnp.array([1,0,0,0,0,0]) 
    action = jnp.repeat(jnp.expand_dims(action, axis=0), batch_size, axis=0)
    print(action.shape)
    print(state.rewards.shape)
    print(state.observation.shape)
    print(state._last_action.shape)
    print(state._e_spawn_speed.shape)
    state = step(state, action)  # state.reward (2,)
```

pgx version would just be the latest one obtainable from pip. 1.4.0 for pgx and 0.2.1 for pgx-minatar.

This is the error message: 
```
Traceback (most recent call last):
  File "test_pgx_envs.py", line 27, in <module>
    state = step(state, action)  # state.reward (2,)
  File "/usr/local/lib/python3.8/dist-packages/pgx/experimental/wrappers.py", line 44, in wrapped_step_fn
    state = step_fn(state, action)
  File "/usr/local/lib/python3.8/dist-packages/pgx/v1.py", line 205, in step
    state = jax.lax.cond(
  File "/usr/local/lib/python3.8/dist-packages/pgx/v1.py", line 208, in <lambda>
    lambda: self._step(state.replace(_step_count=state._step_count + 1), action),  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/pgx_minatar/seaquest.py", line 125, in _step
    return _step(state, action, sticky_action_prob=self.sticky_action_prob)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/pgx_minatar/seaquest.py", line 154, in _step
    action = jax.lax.cond(
TypeError: true_fun and false_fun output must have identical types, got
DIFFERENT ShapedArray(int32[]) vs. ShapedArray(int32[6]).
```

Thanks again for looking into this. Please let me know if I am doing something wrong.

**Comment by sotetsuk** [comment]
This line is wrong 

>  action = jnp.array([1,0,0,0,0,0]) 

Pgx accepts action index not one-hot vector

**Comment by sotetsuk** [comment]
You may also be interested in this PPO example

https://github.com/sotetsuk/pgx/tree/main/examples%2Fminatar-ppo

**Comment by limbryan** [comment]
Great, thanks!
